### ISSUE TITLE
Pom file from maven repo now returning a bunch of html, breaking all builds.

### ISSUE THREAD

**Issue by Ed-HIcks-Branch** [faceterteam/PayCards_Android#49]
https://pay.cards/maven/cards/pay/paycardsrecognizer/1.1.0/paycardsrecognizer-1.1.0.pom

**Comment by krokyze** [comment]
Yep my Bitrise builds are broken now. @vitkuzmenko

**Comment by millenagm** [comment]
+1

**Comment by afomich** [comment]
+1

**Comment by lung9182uk** [comment]
+2

**Comment by LukaKordic** [comment]
```
Could not resolve cards.pay:paycardsrecognizer:1.1.0.
         > Could not parse POM http://pay.cards/maven/cards/pay/paycardsrecognizer/1.1.0/paycardsrecognizer-1.1.0.pom
            > The markup in the document preceding the root element must be well-formed.
```

**Comment by delctrl** [comment]
+3

**Comment by vladislavbakan** [comment]
The same issue, even using [jitpack](https://jitpack.io/) with link to the repo

**Comment by olehsava** [comment]
+4

**Comment by StPatrck** [comment]
+5

**Comment by arnas-savickis** [comment]
+6

**Comment by mkhitarstdev** [comment]
+7

**Comment by domhys** [comment]
+8

**Comment by Mariius** [comment]
+9

**Comment by crazyio** [comment]
+10

**Comment by StPatrck** [comment]
I came up with a temporary fix by simply building the SDK artifact and importing it into my project then declaring the SDK dependencies in my `project/app/build.gradle`.

Import this AAR as a new module in your project or build the artifact yourself and import it:
[paycards-1.1.0.aar.zip](https://github.com/faceterteam/PayCards_Android/files/4723821/paycards-1.1.0.aar.zip)*

Modify your `app/build.gradle` script to include the PayCardsRecognizer dependencies since they're not included in the AAR.

Note this is kotlin gradle dsl and may differ if you are still using groovy.
```
android {
    ....
    dependencies {
        implementation(project(mapOf("path" to "paycards-1.1.0")))
        implementation("com.facebook.device.yearclass:yearclass:2.1.0")
    }
}
```

You should not be able to use the PayCards library without relying on the maven reference.

Hope this helps in the meantime.

*_Had to zip the attached AAR since GitHub doesn't support them. Uncompress before importing into your project_

**Comment by TitanioCorp** [comment]
+11

**Comment by alextrujillo4** [comment]
+12

**Comment by P1nk1** [comment]
+13

**Comment by StPatrck** [comment]
POM file is accessible now. Issue should be close as resolved.

**Comment by kondratk** [comment]
Pom file is unavailable again.

https://pay.cards/maven/com/googlecode/libphonenumber/libphonenumber/8.10.9/libphonenumber-8.10.9.pom
